
name: Maven Package

on:
  push:
    branches: [ "v0.2" ]
  pull_request:
    branches: [ "v0.2" ]

jobs:
  build-linux-x86_64:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kamilalisp-0.2.jar
        path: target/kamilalisp-0.2.jar
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
