
name: Maven Package

on:
  push:
    branches: [ "v0.2" ]
  pull_request:
    branches: [ "v0.2" ]

jobs:
  build-linux-x86_64:
    runs-on: self-hosted
    environment: Main

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -B package -P native --file pom.xml
    - name: Compress the native image with UPX
      run: upx --lzma target/kamilalisp
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kamilalisp-0.2
        path: |
          target/kamilalisp-0.2.jar
          target/kamilalisp
